Add "binary" expression in file open of registration_with_OpenGR example
CGAL/cgal pull request #5290
Opened 2020-12-16 10:46 UTC by maximecharriere

## Summary of Changes
`registration_with_OpenGR` example can't be compilled without this small change:
```c++
std::ifstream input(fname_in1);
```
to
```c++
std::ifstream input(fname_in1, std::ios::binary);
```
`data/hippo1.ply` and `data/hippo2.ply` are in binary_little_endian format. So `read_ply_points` can't read them if they aren't opened in binary mode.

Also add a specific error if a file can't be open and a new argument to pass the output filename

## Release Management

* Affected package(s): Point_set_processing_3

2020-12-17 12:35 UTC, sgiraudot requested changes
I agree with the proposed change (adding the `std::ios::binary` tag) but the diff is way too large for such a small change. Please rewrite your commit without reindenting the whole files you modify (and please use spaces and not tabs for consistency with the rest of the files).

2020-12-22 08:44 UTC, maximecharriere commented
I have revert my changes and only add the `binary` parameter.

2020-12-22 09:19 UTC, MaelRL commented
@maxGimeno If you change the milestone to 5.3, the PR loses its purpose since this was fixed in the IO PR already.

2020-12-22 09:22 UTC, lrineau commented
> @maxGimeno If you change the milestone to 5.3, the PR loses its purpose since this was fixed in the IO PR already.

As the base branch of the PR includes commits from `master` only (like ef13599d963), we cannot merge this PR to anything to `master`, anyway.

2021-01-05 12:46 UTC, MaelRL commented
https://github.com/CGAL/cgal/pull/5323 has the same diff, but targets 5.1. This PR can probably be closed.

2021-01-05 12:48 UTC, sgiraudot commented
Sorry, I completely forgot about this PR, it could also have been rebased…

2021-02-08 17:23 UTC, MaelRL commented
Replaced by #5323.

2021-02-08 17:23 UTC, closed without merging