Fix bash scripts for some tests
CGAL/cgal pull request #5313
Opened 2020-12-30 13:52 UTC by maxGimeno

## Summary of Changes

Don't force cmake options if INIT_FILE is defined, to avoid `Debug` being forced as build_type and flags being overridden

## Release Management

* Affected package(s):Surface_sweep_2, Arrangement_on_surface_2

2021-01-06 12:05 UTC, lrineau requested changes

2021-01-06 12:05 UTC, lrineau commented on Surface_sweep_2/test/Surface_sweep_2/cgal_test_base
>      fi
The indentation seems wrong, now that your editor has replaced tab with two spaces. It seems that file was using tabs of width 8.

2021-01-06 13:12 UTC, lrineau commented on Surface_sweep_2/test/Surface_sweep_2/cgal_test_base
>      fi
The indentation is actually wrong *everywhere* in the two files. Your editor has transformed all <kbd>TAB</kbd> into 2 spaces, instead of 8 spaces.

2021-01-07 08:06 UTC, maxGimeno commented
Al larrangement tests fails at runtime with p1 != p2. I fear they never passed but were previously not tested.

2021-01-14 09:02 UTC, lrineau commented on Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test_with_cmake
> + .  "
```suggestion
 -DCGAL_DIR=\"$CGAL_DIR\" \
 -DCGAL_CXX_FLAGS:STRING=\"$TESTSUITE_CXXFLAGS -I../../include\" \
 -DCGAL_EXE_LINKER_FLAGS=\"$TESTSUITE_LDFLAGS\" \
 -DCMAKE_BUILD_TYPE=NOTFOUND \
 .  "
```

2021-01-14 09:03 UTC, lrineau approved these changes

2021-01-15 08:01 UTC, maxGimeno commented
errors: 
-  https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-41/Surface_sweep_2/TestReport_lrineau_Debian-Stable.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-41/Arrangement_on_surface_2/TestReport_lrineau_ArchLinux.gz

2021-02-05 07:53 UTC, maxGimeno commented
errors remaining in aos2 : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-56/Arrangement_on_surface_2/TestReport_lrineau_ArchLinux.gz

2021-02-15 14:09 UTC, maxGimeno commented
errors https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-61/Arrangement_on_surface_2/TestReport_lrineau_Fedora-rawhide-Release.gz

2021-03-03 14:16 UTC, maxGimeno commented
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-74.shtml

2021-03-03 17:33 UTC, merged