Fix for the PR "CGAL I/O Fix a typo from a copy-paste in deprecated `write_PLY`
CGAL/cgal pull request #5352
Opened 2021-01-14 15:09 UTC by lrineau

_Please use the following template to help us managing pull requests._

## Summary of Changes

_Describe what your pull request changes to CGAL (this can be skipped if it solves an issue already in the tracker or if it is a Feature or Small Feature submitted to the CGAL Wiki)._

## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #0000, fix #0000,...
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

2021-01-14 15:09 UTC, lrineau commented
@maxGimeno Make sure all deprecated function is actually tested, and amend this PR.

2021-01-14 15:11 UTC, sloriot commented
One test that could be done is to try to compile CGAL examples from 5.2 with master.

2021-01-27 18:34 UTC, lrineau commented on BGL/include/CGAL/boost/graph/IO/GOCAD.h
> +  }
I see those lines copy-pasted several times... Should not it be in a function?

2021-02-02 21:58 UTC, lrineau commented
Compilation errors in Github actions checks: https://github.com/CGAL/cgal/pull/5352/checks?check_run_id=1813116033#step:4:4581
> /home/runner/work/cgal/cgal/Stream_support/include/CGAL/IO/OI/Inventor_ostream.h: In function ‘void CGAL::set_default_stream_precision(CGAL::Inventor_ostream_base&, const NP&)’:
/home/runner/work/cgal/cgal/Stream_support/include/CGAL/IO/OI/Inventor_ostream.h:95:7: error: ‘parameters’ has not been declared
   if(!parameters::is_default_parameter(
       ^~~~~~~~~~

2021-02-03 10:53 UTC, maxGimeno commented
fixed

2021-02-04 14:27 UTC, maxGimeno commented
Success in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-55.shtml

2021-02-05 12:42 UTC, MaelRL requested changes

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/GOCAD.h
> +///     \cgalParamDefault{`the precision of the given stream`}
```suggestion
///     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/GOCAD.h
>    return write_GOCAD(os, fname.c_str(), g, np);
```suggestion

  return write_GOCAD(os, fname.c_str(), g, np);
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/GOCAD.h
> +///     \cgalParamDefault{`the precision of the given stream`}
```suggestion
///     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/OBJ.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/OFF.h
> +template <typename Graph>
```suggestion
template <typename Graph>
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/OFF.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/PLY.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/STL.h
> +       \cgalParamDefault{`the precision of the given stream`}
```suggestion
       \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/VTK.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/IO/WRL.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/named_params_helper.h
> +  void set_default_stream_precision(std::ostream& os, const NP& np)
Why "default"? It's more like "set_stream_precision_from_NP".

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/named_params_helper.h
> +         parameters::get_parameter(np, internal_np::stream_precision)))
```suggestion
    if(!parameters::is_default_parameter(get_parameter(np, internal_np::stream_precision)))
```

2021-02-05 12:42 UTC, MaelRL commented on BGL/include/CGAL/boost/graph/named_params_helper.h
> +            parameters::get_parameter(np, internal_np::stream_precision));
```suggestion
      const int precision = parameters::choose_parameter<int>(get_parameter(np, internal_np::stream_precision));
```

2021-02-05 12:42 UTC, MaelRL commented on Maintenance/infrastructure/cgal.geometryfactory.com/crontab
> +#0 * * * * docker inspect --format='{{json .State.Health.Status}}' cgal-mediawiki-docker_wiki_1 | grep -q '"healthy"' || docker logs cgal-mediawiki-docker_wiki_1
Alien change

2021-02-05 12:42 UTC, MaelRL commented on Point_set_3/include/CGAL/Point_set_3/IO/OFF.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Point_set_3/include/CGAL/Point_set_3/IO/PLY.h
> +     \cgalParamDefault{`the precision of the given stream`}
```suggestion
     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Point_set_3/include/CGAL/Point_set_3/IO/XYZ.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Point_set_processing_3/include/CGAL/IO/write_off_points.h
> +      \cgalParamDefault{`the precision of the given stream`}
```suggestion
      \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Point_set_processing_3/include/CGAL/IO/write_ply_points.h
> +       \cgalParamDefault{`the precision of the given stream`}
```suggestion
       \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Point_set_processing_3/include/CGAL/IO/write_xyz_points.h
> +       \cgalParamDefault{`the precision of the given stream`}
```suggestion
       \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Point_set_processing_3/include/CGAL/IO/write_xyz_points.h
> +
```suggestion
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/GOCAD.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/OBJ.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/OFF.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/OFF.h
> +
```suggestion
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/OI/Inventor_ostream.h
> +void set_default_stream_precision(Inventor_ostream_base& os, const NP& np)
just call the other function with os.os()?

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/PLY.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/STL.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/VRML/File_writer_VRML_2.h
> +
```suggestion
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/VRML/File_writer_VRML_2.h
> +                    const bool /*te xtures*/ = false)
```suggestion
                    const bool /*textures*/ = false)
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/VRML/VRML_2_ostream.h
> +void set_default_stream_precision(VRML_2_ostream& os, const NP& np)
same remark as above

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/VTK.h
> +
```suggestion
```

2021-02-05 12:42 UTC, MaelRL commented on Stream_support/include/CGAL/IO/VTK.h
> + *     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Surface_mesh/include/CGAL/Surface_mesh/IO/OFF.h
> +///     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 12:42 UTC, MaelRL commented on Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h
> +///     \cgalParamDefault{`the precision of the given stream`}
```suggestion
 *     \cgalParamDefault{the precision of the stream `os`}
```

2021-02-05 13:08 UTC, maxGimeno commented on Maintenance/infrastructure/cgal.geometryfactory.com/crontab
> +#0 * * * * docker inspect --format='{{json .State.Health.Status}}' cgal-mediawiki-docker_wiki_1 | grep -q '"healthy"' || docker logs cgal-mediawiki-docker_wiki_1
oO

2021-02-18 13:45 UTC, maxGimeno commented
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-65.shtml

2021-02-18 14:32 UTC, merged