Dependency inversion in Iterative_radon of segment_tree.h
CGAL/cgal pull request #5630
Opened 2021-04-19 17:21 UTC by GilesBathgate

## Summary of Changes

The motivation for this PR was initially to suppress a static analysis warning. The error reported was that in the constructor initializer list that `this` is not initialized when reading `dist` since it depends on the member variable  `size` which in turn depends on `end` and `begin` However the initialization order is correct so it's not a problem. I did feel however that the approach here wasn't very conventional, what might be called a code smell, rather than an issue. 

Instead, this PR really is just a tidy up of the `Iterative_radon` class, by moving the dependencies of the generator out of the class it potentially allows different generators to be plugged in if dependency injection is desired for example in unit tests and so on.

## Release Management

* Affected package(s):  Box_intersection_d
* Issue(s) solved (if any): static analysis error. 
* Feature/Small Feature (if any): bugfix/cleaning
* License and copyright ownership: Returned to CGAL authors.

2021-04-19 17:39 UTC, lrineau requested changes
The previous code was right in my opinion.

However, there is a important flaw in your version of the code: the iterator object returned by `iterative_radon` carries a (dangling) reference to the local variable `generator` that is destroyed once the function returns.

2021-04-19 17:43 UTC, GilesBathgate commented
> The previous code was right in my opinion.

I agree it wasn't wrong.
 
> However, there is a important flaw in your version of the code: the iterator object returned by `iterative_radon` carries a (dangling) reference to the local variable `generator` that is destroyed once the function returns.

It doesn't return an `Iterative_radon` its a call to `Iterative_radon::operator()` which returns an `RandomAccessIter` 
IR and Generator are both destroyed with the stack.

2021-04-19 18:55 UTC, lrineau commented
> > The previous code was right in my opinion.
> 
> I agree it wasn't wrong.
> 
> > However, there is a important flaw in your version of the code: the iterator object returned by `iterative_radon` carries a (dangling) reference to the local variable `generator` that is destroyed once the function returns.
> 
> It doesn't return an `Iterative_radon` its a call to `Iterative_radon::operator()(int)` which returns an `RandomAccessIter`
> IR and Generator are both destroyed with the stack.

I am sorry I misinterpreted the code. You are right.

2021-06-17 13:46 UTC, afabri commented
@lrineau as you "misinterpreted", do you now approve the PR, or is there still something to look into?

2021-06-17 13:55 UTC, lrineau commented
I do not object against this PR, even if I think the current version of code (without this PR) was correct. In my opinion, again the static analyzer Giles uses is wrong.

@afabri I let you review the new code, and approve or not. I do not now much about dD Bbox Intersections, and I cannot review the patch easily.

2021-06-17 15:06 UTC, afabri commented
Hi @GilesBathgate  I am wondering why we need this class at all, and why the code is not just right in the function.

2021-06-17 15:10 UTC, GilesBathgate commented
@afabri I think you introduced it here: https://github.com/CGAL/cgal/commit/d966755630f8d4293b311744bf42894a9c90154b It seems like a good pattern to save pushing extra invariant arguments onto the stack.

2021-06-17 16:00 UTC, afabri commented
When  I read it, I missed the recursion.

2021-06-17 16:03 UTC, afabri approved these changes

2021-12-28 08:46 UTC, lrineau approved these changes

2022-01-03 08:45 UTC, sloriot commented
Successfully tested in CGAL-5.4-Ic-125

2022-01-12 11:27 UTC, merged