Doc link issue workaround
CGAL/cgal pull request #5643
Opened 2021-04-27 08:14 UTC by sloriot

Fixes project name linking to CGAL namespace reported in #5600

2021-04-27 13:20 UTC, lrineau requested changes

2021-04-27 13:20 UTC, lrineau commented on Documentation/doc/Documentation/Doxyfile.in
> +PROJECT_NAME = "C&zwj;GAL ${CGAL_DOC_VERSION} - Manual"
I am against that patch. The [zero-width joiner](https://en.wikipedia.org/wiki/Zero-width_joiner) is not made for that sort of thing. "C ZWJ G" should display one letter that is the union of C and G in one letter.

Maybe the [zero-width non-joiner](https://en.wikipedia.org/wiki/Zero-width_non-joiner) could be used, but that is a very nasty visual trick: "C ZWNJ G" should display a ligature of C and G. There might be fonts were that ligature exist.

2021-04-27 13:25 UTC, lrineau commented on Documentation/doc/Documentation/Doxyfile.in
> +PROJECT_NAME = "C&zwj;GAL ${CGAL_DOC_VERSION} - Manual"
Even with the [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) the effect will be to break CGAL into two words: "C" and "GAL", but joined by a zero-width space. Even that is a nasty visual trick. Why this workaround, by the way?

2021-06-17 14:46 UTC, sloriot commented
Do you prefer going with a %CGAL removed with post-processing?

2021-06-17 20:05 UTC, lrineau commented
> Do you prefer going with a %CGAL removed with post-processing?

I think that would be a better option than using special spaces incorrectly.

2021-06-29 16:54 UTC, sloriot commented
Fixed by the latest commit. However I notice that the navtree of the main page is re-broken
![Screenshot from 2021-06-29 18-41-46](https://user-images.githubusercontent.com/1224632/123837658-65c1cf00-d90b-11eb-928f-ce3e435fda6b.png)
There is an extra duplicated layer. Maybe it has to do with our navtree.js hacks...

2021-06-29 17:01 UTC, sloriot commented
Does not seem related. Commenting our hacks does not change anything. @albert-github do you know if it can be a regression in doxygen?

2021-06-29 17:10 UTC, albert-github commented
I didn't yet dive into it but from which version is the picture shown?

2021-06-29 17:25 UTC, albert-github commented
I dove a little bit in it. The choice for `&zwj;` or maybe better `&zwnj;` is because they are handled properly in the headers and index lists whilst this is not the case with the `%` sign (also commands are not handled in the headers / index lists). The reason for using the `%CGAL` is to make a distinction between the CGAL product and the CGAL namespace (without the `%` there might be an unintended link to the namespace).

Although `&zwj;` / `&zwnj;` are not that nice I personally favor them over postprocessing steps as shown in this patch.
(This is not an easy problem to fix).

2021-07-01 06:24 UTC, sloriot commented
> I didn't yet dive into it but from which version is the picture shown? and what is the page name `<pck>/<file>.html`?

I'm using Doxygen master latest HEAD. Actually, I tried it again and I noticed that it is the fact of adding the % that is breaking the navtree. 

I don't know what to do. @lrineau ?

2021-07-01 06:37 UTC, lrineau commented
The incorrect usage of "invisible spaces" is really something I do not want to see spread. Would it work to have a macro `\cgal`, to design CGAL as a library or a project, and then `CGAL` would be restricted to the CGAL namespace? That macro `\cgal` could use a [zero-width non-joiner](https://en.wikipedia.org/wiki/Zero-width_non-joiner). The issue with that zero-width non-joiner, is that the browser will be allowed to add a line break between "C" and "GAL".

2021-07-01 07:03 UTC, sloriot commented
The macro won't work for the project name as it is used in doxygen config file. Let me try to disable the link to CGAL.

2021-07-01 07:55 UTC, sloriot commented
I was thinking of using `EXCLUDE_SYMBOLS` but then the namespace CGAL is totally ignored so it is not a good solution. We could disable automatic link with  `AUTOLINK_SUPPORT=OFF` but then we would require to explicitly add `\ref` everywhere we want a link to be generated. Still no solution but the one suggested by @albert-github with drawbacks mentioned by @lrineau.

2021-08-31 06:54 UTC, lrineau commented
@sloriot This is the third (and last PR) I have revived. It was closed by error when I deleted the branch `5.1.x-branch` from Github. I have reassigned it to `5.2.x-branch`.

2021-12-14 15:27 UTC, closed without merging