FindTBB is no longer compatible with oneTBB 2021.1.1
CGAL/cgal pull request #5948
Opened 2021-08-31 15:21 UTC by maximecharriere

Since oneTBB 2021.1.1, `/tbb/tbb_stddef.h` no longer exists.  
The version can be found in [/oneapi/tbb/version.h](https://github.com/oneapi-src/oneTBB/blob/master/include/oneapi/tbb/version.h)

2021-08-31 18:34 UTC, maximecharriere commented
<tbb/tbb_config.h> no longer exists either, which causes me to get errors when building the Polyhedron demo. 

![image](https://user-images.githubusercontent.com/51918753/131557284-3f9c7df7-8cba-4d67-ad02-b115da126b95.png)

Due to this line :

https://github.com/CGAL/cgal/blob/6f7fd79a1e714937c9a29fd3b4e3d6de225e1922/STL_Extension/include/CGAL/thread.h#L37

2021-09-01 13:38 UTC, maxGimeno commented
I find it strange that you have this kind of problems. Since #5732 oneTBB should be found with the cmake stuff they provide. The rest of the file only serves for 2019 versions or something. 

Anyway, applying your patch would probably break compatibility with every version of TBB except oneTBB 2021

2021-09-01 14:00 UTC, maxGimeno commented
After discussions with @lrineau, it appears that CGAL is not yet compatible with oneTBB 2021, in the code. But an easy workaround for your bug is to specify the right TBB_DIR to cmake when configuring the Polyhedron Demo.
for example, on my testing machine, it is `-DTBB_DIR=C:/dev/OneAPI/tbb/2021.2.0/lib/cmake/tbb"`

2021-09-01 14:10 UTC, lrineau commented
> After discussions with @lrineau, it appears that CGAL is not yet compatible with oneTBB 2021, in the code. But an easy workaround for your bug is to specify the right TBB_DIR to cmake when configuring the Polyhedron Demo.
> for example, on my testing machine, it is `-DTBB_DIR=C:/dev/OneAPI/tbb/2021.2.0/lib/cmake/tbb"`

We are working on making the next bug-fix release CGAL-5.3.1 (not yet released) compatible with TBB. See for example PRs https://github.com/CGAL/cgal/pull/4892 and https://github.com/CGAL/cgal/pull/5850.

But we have not yet modified our documentation. TBB from oneAPI should be found by CMake using the config mode of `find_package`.


... I have a deja-vu impression actually... We already discussed that with you, @maximecharriere, in https://github.com/CGAL/cgal/issues/5676! See my answer at https://github.com/CGAL/cgal/issues/5676#issuecomment-832833724.

2021-09-01 14:11 UTC, lrineau requested changes
This change would prevent anybody from using TBB-2019 or TBB 2020.

2021-09-10 15:52 UTC, sloriot commented
Replaced by #5953

2021-09-10 15:52 UTC, closed without merging