PMP doc fixes and enhancements
CGAL/cgal pull request #6389
Opened 2022-03-07 14:35 UTC by MaelRL

## Summary of Changes

Spring cleaning for PMP's doc.

## Release Management

- [ ] Post-merge: handle group label changes 
hole_filling_grp -> PMP_hole_filling_grp 
measure_grp -> PMP_measure_grp
keep_connected_components_grp -> PMP_keep_connected_components_grp

* Affected package(s):  `PMP`
* Issue(s) solved (if any): fix #6385
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

2022-03-07 14:37 UTC, MaelRL commented
/build:v0

2022-03-08 09:01 UTC, MaelRL commented
/build:v1

2022-03-09 18:40 UTC, sloriot commented
Successfully tested in CGAL-5.5-Ic-36

2022-03-14 08:55 UTC, afabri requested changes

2022-03-14 08:55 UTC, afabri commented on Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h
> + * and orients it (using `orient_polygon_soup()`) as to obtain a polygon mesh.
I would still suggest to add a sentence like     "If there is no need to orient and repair the input you should use the function   `CGAL::IO::read_polygon_mesh()`"

2022-03-29 15:35 UTC, sloriot commented
Successfully tested in CGAL-5.5-Ic-50

2022-03-30 07:24 UTC, merged