Add do_intersect for convex hulls
CGAL/cgal pull request #6557
Opened 2022-05-04 17:08 UTC by sloriot

## Summary of Changes

Add convex hull do-intersect predicates based on [this paper](https://doi.org/10.1016/j.cad.2017.05.009).

## Release Management

* Affected package(s): Convex_hull_3
* Feature/Small Feature (if any): TODO
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership: INRIA Nancy

**TODOs:**
- [ ] Small features
- [ ] CGALize code
- [ ] Import GJK for `separation_distance()`
- [ ] Check the improved GJK, see [here](https://dl.acm.org/doi/10.1145/3072959.3083724)
- [ ] Import dedicated code for OBBs

2025-05-16 08:08 UTC, afabri requested changes
This is a first round of review. I did not look into the algorithm itself yet.

2025-05-16 08:08 UTC, afabri commented on Convex_hull_3/test/Convex_hull_3/ch3_test_do_intersect.cpp
> +    auto random_point=[&](){
Use the generators from [this package](https://doc.cgal.org/latest/Generator/index.html#Chapter_Geometric_Object_Generators).

2025-05-16 08:08 UTC, afabri commented on Convex_hull_3/test/Convex_hull_3/ch3_test_do_intersect.cpp
> +  void test_random_tetrahedrons(int N, CGAL::Random &r)
```suggestion
  void test_random_tetrahedra(int N, CGAL::Random &r)
```

2025-05-16 08:08 UTC, afabri commented on Convex_hull_3/test/Convex_hull_3/ch3_test_do_intersect.cpp
> +  CGAL::Random rp;
not used.

2025-05-16 12:00 UTC, LeoValque commented on Convex_hull_3/include/CGAL/convex_hull_with_hierarchy.h
> +        if(compare(tmax, p)==SMALLER){
It is a comparison between Value not between Points, 'p' is probably a bad name, I shoud probably replace by 't' or 'cp'.

2025-05-16 12:08 UTC, LeoValque commented on Convex_hull_3/test/Convex_hull_3/ch3_test_do_intersect.cpp
> +  CGAL::Random rp;
It is used in the next line, I can probably replace it by 'get_default_random()' in the next line.

2025-05-21 07:02 UTC, LeoValque commented on Convex_hull_3/include/CGAL/convex_hull_with_hierarchy.h
> +  typedef Surface_mesh< P > Mesh;
I keep the typedef for Point because I use it to deduce the kernel in do_intersect

2025-05-22 15:17 UTC, afabri commented
/build:v0

2025-05-22 15:31 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +FT separation_distance(const PointRange& r1, const PointRange& r2,
@MaelRL do we have to prefix with ` compute_` ?

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `IncidentGraph`.}
```suggestion
*     \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `AdjacencyGraph`.}
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +* @param ch2 the second hull convex considered in the do-intersect test
```suggestion
* @param ch1 the first convex hull
* @param ch2 the second convex hull 
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `IncidentGraph`.}
Must it be available in the  `MutableFaceGraph` of the hierarchy??

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `AdjacencyGraph`.}
```suggestion
*     \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `Graph`.}
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamDescription{A Converter from the point type of `vertex_point_map` to the point type of `geom_traits`}
```suggestion
*     \cgalParamDescription{A converter from the point type of `vertex_point_map` to the point type of `geom_traits`}
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamDefault{a \cgal `Cartesian_converter` deduced from vertex_point_map and `geom_traits`, using `CGAL::Kernel_traits`}
```suggestion
*     \cgalParamDefault{a \cgal `Cartesian_converter` deduced from ` vertex_point_map`  and `geom_traits`, using `CGAL::Kernel_traits`}
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamDefault{a \cgal `Cartesian_converter` deduced from point_map and `geom_traits`, using `CGAL::Kernel_traits`}
```suggestion
*     \cgalParamDefault{a \cgal `Cartesian_converter` deduced from ` point_map` and `geom_traits`, using `CGAL::Kernel_traits`}
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +* @tparam PointRange: is a model of `ConstRange`. The value type of its iterator is the key type of the named parameter point_map.
```suggestion
* @tparam PointRange: is a model of `ConstRange`. The value type of its iterator is the key type of the named parameter `point_map`.
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +* @param r1 range points of the first convex considered in the do-intersect test
```suggestion
* @param r1 first point range
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*                           If this value is not `0`, then an intersection might be reported even if the convex hulls does not intersect.
```suggestion
*                           If this value is not `0`, then an intersection might be reported even if the convex hulls do not intersect.
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamType{an positive integer convertible to `std::size_t`}
```suggestion
*     \cgalParamType{a positive integer convertible to `std::size_t`}
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +* provides a lower bound on the distance between the two convex. Consider the convex hull of point sets provide.
```suggestion
* provides a lower bound on the distance between two convex sets. Consider the convex hull of point sets provide.
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +* such that it exists a function 'extreme_point(M, Kernel::Vector_3, Converter)' returning a Kernel::Point_3
```suggestion
* such that exists a function 'extreme_point(M, Kernel::Vector_3, Converter)' returning a Kernel::Point_3
```

2025-05-22 16:13 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +* @param c2 second convex considered in the do-intersect test
```suggestion
* @param c1 first convex set considered in the do-intersect test
* @param c2 second convex set considered in the do-intersect test
```

2025-05-22 16:18 UTC, LeoValque commented on Convex_hull_3/include/CGAL/Convex_hull_3/predicates.h
> +*     \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `IncidentGraph`.}
I guess this would mean you have to provide a `vertex_point_map` if you're using a minimal `AdjacencyGraph`

2025-05-23 05:42 UTC, afabri commented
/build:v2

2025-05-23 06:22 UTC, afabri commented
/build:v2

2025-05-23 06:41 UTC, afabri commented
/force-build:v2

2025-05-23 06:49 UTC, afabri commented
/force-build:v2

2025-05-23 07:04 UTC, afabri commented
With the current version of the [documentation](https://cgal.github.io/6557/v2/Convex_hull_3/group__PkgConvexHull3Ref.html) we see that `extreme_point()` should probably get a suffix `_3`. And it should not be in a sub namespace. @sloriot ?

2025-05-23 13:13 UTC, LeoValque commented
/force-build:v2

2025-06-04 09:50 UTC, LeoValque commented
/build:v3

2025-06-04 12:08 UTC, LeoValque commented
/forcce-build:v3

2025-06-04 12:08 UTC, LeoValque commented
/force-build:v3

2025-09-03 14:33 UTC, sloriot commented
Successfully tested in CGAL-6.1-Ic-230

2025-12-05 09:15 UTC, sloriot commented
@LeoValque could you please tick the TODOs at the beginning of the PR?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/benchmark/Convex_hull_3/CMakeLists.txt
> +project(Periodic_2_triangulation_2_Benchs)
copy/paste error

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/benchmark/Convex_hull_3/CMakeLists.txt
> +find_package(Eigen3 3.1.0 REQUIRED) #(3.1.0 or greater)
merge main and apply changes from https://github.com/CGAL/cgal/pull/9112

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +@todo Add \ cgalCite{TODO}.
TODO

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +Input convex hulls can be provided in three forms: as range of points, as graph of points or as instance of the `Convex_hull_hierarchy` class.
graph of points?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +The `do_intersect()` functions provide an implementation of the algorithm computing the intersection of two convex hulls by searching on the 2-sphere
As you did not prefix it with the namespace, there is a risk that it picks the one from the kernel.

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not or checking if two convex d
```suggestion
\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not, and checking if two convex hulls intersect. One can compute the convex hull of a set of points in three dimensions in two ways: using a static algorithm or using a triangulation to get a fully dynamic computation.}
```

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not or checking if two convex d
3 ways then with the new data structure?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +points in is strongly convex or not or checking if two convex do intersect.  This chapter describes the functions
```suggestion
points in is strongly convex or not, and checking if two convex hulls intersect.  This chapter describes the functions
```

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +points in is strongly convex or not or checking if two convex do intersect.  This chapter describes the functions
what about separation distance?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not or checking if two convex d
what about separation distance?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
needed?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +  return is_negative(dot(cross(edge, normal), pt));
exact constructions neeeded, no predicate only version?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +Vector_3 triangle_dir_to_origin(boost::container::small_vector<Vector_3, 4>& simplex, const K &k){
seems exact predicates are also needed

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +Vector_3 triangle_dir_to_origin(boost::container::small_vector<Vector_3, 4>& simplex, const K &k){
I have the question for all functions in the namespace

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +* provides a lower bound on the squared distance between the convex hulls of the two point sets.
separating is important here, cause someone could think about penetration depth

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +* @param r1 first point range
convex?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +* @tparam AdjacencyGraph: is a model of `AdjacencyGraph`.
```suggestion
* @tparam AdjacencyGraph is a model of `AdjacencyGraph`.
```

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +* @tparam PolygonMesh: is a model of `MutableFaceGraph`, more details in `CGAL::Convex_hull_hierarchy`
mutable really?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +  //The function need exact computation to works correctly
This should be indicated clearly somewhere. What happen if we are using EPICK? Since it is a lower bound, can't we use intervals?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +#ifndef CGAL_CONVEX_HULL_3_INTERSECTIONS_H
`do_intersect.h`?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +#include <CGAL/Real_timer.h>
debug only

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +inline constexpr bool is_instance_of_v = false;
namespace pollution

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +template<class Convex,
if this part is the same as CH3, it should be put in a helper file and included by both files. Btw, Sven recently updated it in `main`.

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +* computes the furthest point of the convex graph along the direction.
```suggestion
* computes the furthest point of the convex graph along the direction `dir`.
```

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +* \pre The input graph must represent a convex object to guarantee a correct answer.
not strict I guess?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +Point_3 extreme_point_3(const Graph& g, const Direction_3 &dir, const NamedParameters &np);
strange it's not a vertex descriptor

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +    // PRECONDITION : all vertex are normalized.
vectors?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +      case 2 :{   // The two vertex are opposite so we do not take their mean
```suggestion
      case 2 :{   // The two vertices are opposite so we do not take their mean
```

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +* checks if the convex hulls of the two point sets intersect or not.
does the points need to be only on the convex hull? strictly?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +* @param r1 range points of the first convex considered in the do-intersect test
points of the first convex hull

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +*   \cgalParamNBegin{geom_traits}
exact constructions needed?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +inline constexpr bool has_property_map = false;
global scope pollution

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  /// This class implements a convex hull with a data structure optimized for finding the extreme point of the convex
the class stores a convex hull with some properties, it does not implement it?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  /// @tparam PolygonMesh The polygon mesh structure used to construct each level of the hierarchy. Must be a model of ` MutableFaceGraph`.
```suggestion
  /// @tparam PolygonMesh The polygon mesh structure used to construct each level of the hierarchy. Must be a model of `MutableFaceGraph`.
```

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  typedef typename PolygonMesh::Point Point;
missing VPM as template parameter?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * computes the furthest point of the convex hull along the direction.
constructs

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  typename Kernel_traits<Direction_3>::Kernel::Point_3 extreme_point_3(const Direction_3 &dir, const NamedParameters & np=parameters::default_values) const {
why is the output type not fixed?

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +    Random rng;
init it to get_default_random() and provide a way to set it.

2025-12-05 10:02 UTC, sloriot commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +      Property_map pm=new_sm.template add_property_map<vertex_descriptor>("v:next_in_hierarchy", *(vertices(above_sm).begin())).first;
Surface_mesh only

2025-12-09 16:55 UTC, LeoValque commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +Input convex hulls can be provided in three forms: as range of points, as graph of points or as instance of the `Convex_hull_hierarchy` class.
a graph with a vertex_point_map, Is it clearer?

2025-12-09 17:14 UTC, LeoValque commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +* @param r1 first point range
It will works correctly if the points are not in a convex position.

2025-12-09 17:30 UTC, LeoValque commented on Convex_hull_3/include/CGAL/Convex_hull_3/intersections.h
> +*   \cgalParamNBegin{geom_traits}
Exact_predicate is needed.

2025-12-10 07:40 UTC, sloriot commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +Input convex hulls can be provided in three forms: as range of points, as graph of points or as instance of the `Convex_hull_hierarchy` class.
not really, a graph model of `XXX`

2026-01-27 11:48 UTC, LeoValque commented
/build:v1

2026-01-27 13:09 UTC, afabri commented
Please fix the pre-existing doc bug of the missing comme in the template parameter list [here](https://cgal.github.io/6557/v1/Convex_hull_3/group__PkgConvexHull3Functions.html#ga52fca4745c2ef0351063fbe66b035fd1)

2026-01-27 13:20 UTC, afabri requested changes

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +Point_3 extreme_point_3(const Graph& g, const Direction_3 &dir, const NamedParameters &np);
`Point_3` is not defined

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam Graph: is a model of `AdjacencyGraph`.
Can you confirm that you do not iterate over the vertices?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * @tparam `Direction_3` model of `Kernel::Direction_3`. The kernel does not require to be the same than the one using by the Mesh
```suggestion
  * @tparam Direction_3 model of `Kernel::Direction_3`. The kernel does not require to be the same as the one used by the Mesh
```
Which mesh?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * \return Return a `Point_3` using the same kernel as the direction.
```suggestion
  * \return  a `Point_3` using the same kernel as the direction.
```

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * constructs the furthest point of the convex hull along the direction.
I grepped the words farthest and furthest and saw that we use them both.  We probably should only furthest like here. @albert-github ?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  typename Kernel_traits<Direction_3>::Kernel::Point_3 extreme_point_3(const Direction_3 &dir, const NamedParameters &np=parameters::default_values) const {
@MaelRL do we want a geomtric traits class instead of a template parameter `Direction_3` ?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam Direction_3: is a model of CGAL::Direction_3.
```suggestion
* @tparam Direction_3: is a model of `Kernel::Direction_3`.
```

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam Graph: is a model of `AdjacencyGraph`.
Also you have to write that there must be a vertex property map

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam PointRange is a model of `ConstRange`. The value type of its iterator is the key type of the named parameter ` point_map`.
```suggestion
* @tparam PointRange is a model of `ConstRange`. The value type of its iterator is the key type of the named parameter `point_map`.
```

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  ///  is optimized for very fast intersection tests.
```suggestion
  ///  is optimized for fast intersection tests.
```

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  /// @tparam PolygonMesh The polygon mesh structure used to construct each level of the hierarchy. Must be a model of `MutableFaceGraph`.
```suggestion
  /// @tparam PolygonMesh The polygon mesh used to construct each level of the hierarchy. Must be a model of `MutableFaceGraph`.
```

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  /// @tparam PolygonMesh The polygon mesh structure used to construct each level of the hierarchy. Must be a model of `MutableFaceGraph`.
Does it not also have requirements on the point type?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  ~Convex_hull_hierarchy(){
Appears in the documentation, although not documented. Can we switch that off, or do we have to put a preprocessor macro here? @sloriot

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +            typename NamedParameters=parameters::Default_named_parameters>
Do we really need this function?  There is the free function for that, so this is private and the free function a friend.

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +    using GTC=typename internal_np::Lookup_named_param_def <
@MaelRL do we want to be picky on a space before and after an assignment?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/package_info/Convex_hull_3/dependencies
> +Kernel_d
Why do we need this?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not, checking if two convex hul
```suggestion
\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not, checking if two convex hulls intersect and computing the distance between them if they do not. One can compute the convex hull of a set of points in three dimensions in three ways: using a static algorithm, using a triangulation to get a fully dynamic computation or using the specific data structure `Convex_hull_hierarchy` for optimal intersection testing.}
\cgalPkgManuals{Chapter_3D_Convex_Hulls,PkgConvexHull3Ref}
```

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +The `CGAL::Convex_hull_3::do_intersect()` functions provide an implementation of the algorithm computing the intersection of two convex hulls by searching on the 2-sphere \cgalCite{hornus2017convexin
why "computing the intersection"here?

2026-01-27 13:20 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +\section Convex_hull_3Do_intersect Intersection test of Convex Hulls
```suggestion
\section Convex_hull_3Do_intersect Intersection Test of Convex Hulls
```

2026-01-27 14:27 UTC, LeoValque commented
/force-build:v1

2026-01-29 07:09 UTC, afabri commented
`separation_distance()`  is not a predicate.

2026-01-29 07:12 UTC, afabri commented
Can separation distance also distinguish between intersection of the interior and touching?

2026-01-29 07:13 UTC, afabri commented
You also have to say where the point type comes  from.   Should be the value type of the range, I guess.

2026-01-29 07:19 UTC, afabri commented
For the `Convex_hull_hierarchy`  we must explain when it makes sense to use them.   What is the time to construct it? How many intersection tests do we have to perform now, so that there is a total performance gain.  
Can we say that the size of the hierarchy is the roughly the double of the input size ?
Do the hulls in the levels bound from inside or from outside?

2026-01-30 17:33 UTC, LeoValque commented
/build:v3

2026-01-30 17:40 UTC, LeoValque commented
/build:v4

2026-02-01 18:34 UTC, LeoValque commented
/force-build:v4

2026-02-01 19:26 UTC, LeoValque commented
/force-build:v4

2026-02-01 19:53 UTC, LeoValque commented
/force-build:v4

2026-02-02 07:31 UTC, afabri requested changes

2026-02-02 07:31 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +When many intersection queries are required, a `CGAL::Convex_hull_hierarchy` can be constructed to accelerate intersection tests, particularly when the convex hull has a large number of vertices (see
```suggestion
When many intersection queries are  performed on a convex hull, a `CGAL::Convex_hull_hierarchy` can be constructed for it to accelerate intersection tests, particularly when the convex hull has a large number of vertices (see `CGAL::Convex_hull_hierarchy` for more details).
```

2026-02-02 07:31 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
>  \section Convex_hull_3Performance Performance
You should add a section with the implementation history  like for [ABB Tree](https://doc.cgal.org/latest/AABB_tree/index.html#aabb_tree_history)

2026-02-02 07:31 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not, checking if two convex hul
Finally no distance computation.

2026-02-02 07:31 UTC, afabri commented on Convex_hull_3/include/CGAL/extreme_point_3.h
> +* computes the furthest point of the convex graph along the direction `dir` and returns the associated vertex.
```suggestion
* computes the furthest point of the convex graph along the direction and returns the associated vertex.
```

The other overloads do not have `dir`.

2026-02-02 07:31 UTC, afabri commented on Convex_hull_3/include/CGAL/extreme_point_3.h
> +* computes the furthest point of the convex graph along the direction `dir` and returns the associated vertex.
How are ties broken in case there are several furthest points?   Or can we get the information that it is an edge or face.

2026-02-02 07:31 UTC, afabri commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +*   \cgalParamNBegin{number_of_iterations}
What is the trade-off for few iterations?  Does one more iteration make it a little better, or a lot? For what number of iterations do I get the correct result?     My guess is that this is related to the hierarchy. And related to the fact that the hierarchy is from inside (Did I get a reply when I asked inside or outside?).

2026-02-02 08:14 UTC, afabri commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +Input hulls can be provided in three forms: as range of points, as graph model of `Vertex_list_graph` and `AdjacencyGraph` or as instance of the `Convex_hull_hierarchy` class.
```suggestion
Input hulls can be provided in three forms: as range of points, as graph model of `VertexListGraph` and `AdjacencyGraph` or as instance of the `Convex_hull_hierarchy` class.
```

2026-02-02 10:35 UTC, MaelRL commented
/force-build:v4

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +Input convex hulls can be provided in three forms: as range of points, as graph model of `AdjacencyGraph` or as instance of the `Convex_hull_hierarchy` class.
```suggestion
Input convex hulls can be provided in three forms: as a range of points, as a graph model of `AdjacencyGraph`, or as an instance of the `Convex_hull_hierarchy` class.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +The `CGAL::Convex_hull_3::do_intersect()` functions provide an implementation of the algorithm computing the intersection of two convex hulls by searching on the 2-sphere \cgalCite{hornus2017convexin
I would separate the fact that you're detecting intersections from how you are doing it as to not create confusion on the fact that it's not a specific type of intersections.

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +A `Convex_hull_hierarchy` can be constructed from either a range of points or a mesh. During construction, it is assumed that the resulting convex hull is non-degenerate.
That feels like a bit too many details.

If Convex_hull_hierarchy is much better, should other inputs always be wrapped into this?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalCRPSection{Predicates}
this should come later than the main functions

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +When many intersection queries are  performed on a convex hull, a `CGAL::Convex_hull_hierarchy` can be constructed for it to accelerate intersection tests, particularly when the convex hull has a lar
```suggestion
\section Convex_hull_3Do_intersect Intersection Test of Convex Hulls

`CGAL::Convex_hull_3::do_intersect(ch1, ch2)` determines whether two convex hulls intersect or not.

Input hulls can be provided as a range of points or as a graph, and may be of different types. Furthermore, when many intersection queries use the same object, one should wrap that input in the class `CGAL::Convex_hull_hierarchy` as to construct an optimized view of the convex hull and accelerate intersection tests. This is especially true when the convex hull is made of a large number of vertices (see `CGAL::Convex_hull_hierarchy` for more details).
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +The initial version of this package was implemented by Susan Hert and Stefan Schirra and released in 2011.
```suggestion
The initial version of this package was implemented by Susan Hert and Stefan Schirra, and released in 2011.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +The functions `do_intersect()`, `extreme_point_3()` and the class `Convex_hull_hierarchy` were implemented in 2026 by Samuel Hornus and Leo Valque, under the supervision of Sébastien Loriot.
```suggestion
The functions `do_intersect()`, `extreme_point_3()`, and the class `Convex_hull_hierarchy` were implemented in 2026 by Samuel Hornus and Leo Valque, under the supervision of Sébastien Loriot.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalPkgDesc{This package provides functions  for computing convex hulls in three dimensions as well as functions for checking if sets of points are strongly convex or not, checking if two convex hul
```suggestion
\cgalPkgDesc{This package provides functions for computing convex hulls in three dimensions, as well as functions for checking if sets of points are strongly convex or not, and checking if two convex hulls intersect or not. One can compute the convex hull of a set of points in three dimensions in three ways: using a static algorithm, using a triangulation to get a fully dynamic computation, or using the specific data structure `Convex_hull_hierarchy` for optimal intersection testing.}
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +points in is strongly convex or not, checking if two convex hulls intersect and computing the distance between them if they do not.  This chapter describes the functions
```suggestion
points in is strongly convex or not and checking if two convex hulls intersect. This chapter describes the functions
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt
> +\cgalCRPSection{Intersection Test}
That's too many sections now with some function & classes that belong together but are split.

I'd do something like:

Section: Concepts

Section: Traits
- `CGAL::Convex_hull_traits_3<R>`
- `CGAL::Extreme_points_traits_adapter_3`
- make_extreme_points_traits_adapter()

Section: Convex hull

- convex_hull()

Section: Extreme points

- extreme_points()
- extreme_point()
- extreme_vertex()

Section: Convexity Checking Function
...

Section: Intersection

- `CGAL::Convex_hull_3::do_intersect()`
- `CGAL::Convex_hull_hierarchy`

Section: Halfspace etc.
...

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/examples/Convex_hull_3/do_intersect_ch3.cpp
> +  // Convex_hull_hierarchy is data structure for fast intersection test of Convex_hull
```suggestion
  // When performing many intersection tests, we can construct an optimized version of the convex hull with the class `Convex_hull_hierarchy`
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam Convex_1 same as Convex_2
```suggestion
* @tparam Convex_2 same as `Convex_1`
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam Convex_1 same as Convex_2
\+ you use \tparam `Convex_1` in the doc, but `Convex1` in the code.

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* @tparam Convex_1 is a model of `ConstRange` or a model of `VertexListGraph` and `AdjacencyGraph` or an instance of `CGAL::Convex_hull_hierarchy`
make it a list for readability

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* They are not required to use the same input type.
You're missing the explanation on why one should use the hierarchy.

I would simply copy paste the user manual.

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +*                     If this parameter is omitted, an internal property map for `CGAL::vertex_point_t` must be available in `Convex_1` (`Convex_2`).}
You can use multiple "Extra"s

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  /// \f$O(\sqrt{n})\f$ on average for a graph and \f$O(\log{n})\f$ on average for a Convex_hull_hierarchy, where \f$n\f$ is the number of points of the object.
```suggestion
  /// \f$O(\sqrt{n})\f$ on average for a graph, but only \f$O(\log{n})\f$ on average for a `Convex_hull_hierarchy`, where \f$n\f$ is the number of points of the object.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * constructor taking the points associated to the vertices of  `g`.
```suggestion
  * Constructor taking the points associated to the vertices of `g`.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * @tparam NamedParameters: a sequence of named parameters
```suggestion
  * @tparam Graph a model of `VertexListGraph`
  * @tparam NamedParameters a sequence of named parameters
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  ///         An internal property map for ` CGAL::vertex_point_t` must be available, with a value type that is a model of `Kernel::Point_3`.
```suggestion
  ///         An internal property map for `CGAL::vertex_point_t` must be available, with a value type that is a model of `Kernel::Point_3`.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *     \cgalParamType{a model of `ReadWritePropertyMap` whose value type is a point type}
Why do you need writable?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *     \cgalParamType{bool}
```suggestion
  *     \cgalParamType{Boolean}
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *     \cgalParamExtra{If set to `false`, `g` must be convex.}
```suggestion
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *     \cgalParamDescription{If set to `true`, the convex hull of `g` is compute. Otherwise, `g` is supposed to be convex.}
```suggestion
  *     \cgalParamDescription{If set to `true`, the convex hull of `g` is computed. Otherwise, `g` must be convex.}
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *     \cgalParamDescription{Define the seed used by}
```suggestion
  *     \cgalParamDescription{Define the seed used by the hierarchy.}
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +    Random rng = (seed != 0)?Random(seed):get_default_random();
You should use `is_default_parameter` instead, because otherwise you ignore the seed if someone passes "0"

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +    bool compute_convex_hull = parameters::choose_parameter(parameters::get_parameter(np, internal_np::compute_convex_hull), true);
naive question: Can we add `precondition(is_strongly_convex)`, or there is some gap between what we require here and that function?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * constructor taking the points in the range `[first, last)`.
```suggestion
  * Constructor taking the points in the range `[first, last)`.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy_3.h
> +  * \cgalNamedParamsEnd
no traits?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * @tparam Traits must be a model of the concept ConvexHullTraits_3. For the purposes of checking the postcondition that the convex hull is valid,
Could you please fix the alignment issue on the reference manual page for convex_hull_traits_3: the "is model of" is not where it should be (probably just a line break to add).

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *         `Traits` must also be a model of the concept `IsStronglyConvexTraits_3`. Furthermore, `Traits` must define a type `PolygonMesh` that is a model of `MutableFaceGraph`.
"`Traits` must define a type `PolygonMesh` etc." is obsolete?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  // /// returns the number of the higher level of the hierarchy.
I see the "private", but even for devs: the sentence must be rewritten for clarity

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  }
Seems somewhat dangerous since I'd assume the whole thing breaks if you modify the mesh?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * @tparam Direction_3 model of `Kernel::Direction_3`. The kernel does not require to be the same as the one used by the Mesh
```suggestion
  * @tparam Direction_3 model of `Kernel::Direction_3`. The kernel is not required to be the same as the one used by `PolygonMesh`
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * @tparam Direction_3 model of `Kernel::Direction_3`. The kernel does not require to be the same as the one used by the Mesh
Even if not the same, you need either implicit/explicit convertibility, or you need requirements on the kernel deduced from this type (which also forces your type to come from a CGAL kernel).

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * constructs the furthest point of the convex hull along the direction and returns the corresponding vertex.
"Furthest" is defined how, with the orthogonal projection onto the direction? Maybe there's a clearer definition?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +* computes the furthest point of the convex hull along the direction; If not unique, a single vertex is returned.
```suggestion
* computes the furthest point of the convex hull along the direction.
* If not unique, a single vertex is returned.
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +* @tparam Direction_3: is a model of CGAL::Direction_3.
`CGAL::Direction_3` is not a concept. Cf other function.

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +#if DOXYGEN_RUNNING
There is no need to hide the graph traits: these are documented mechanisms.

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +* @tparam Mesh a model of `VertexListGraph` and `MutableFaceGraph` used by`CGAL::Convex_hull_hierarchy`
```suggestion
* @tparam Mesh a model of `VertexListGraph` and `MutableFaceGraph`
```

Why mutable?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +*   \cgalParamNBegin{geom_traits_converter}
Maybe we could simplify to something like:

```cpp
/// \tparam PolygonMesh must be (...)
/// \tparam Traits must be a model of (...). By default, a kernel is deduced from the internal point map of PolygonMesh
template <typename PolygonMesh, typename Traits = CGAL::Default>
struct Convex_hull_hierarchy
{
  using Geom_traits = Traits;

  [...]

  /// \tparam Graph must be a model of (...)
  ///  \tparam Direction must be a `Kernel::Direction_3` from a \cgal kernel
  template <class Graph, class Direction, class NamedParameters>
  typename boost::graph_traits<Graph>::vertex_descriptor
  extreme_vertex_3(const Convex_hull_hierarchy<Mesh> &ch, 
                                   const Direction& dir,
                                   const NamedParameters &np);
```

The template param + public type would clarify things at a few places.

And is there really a need to do the "geom_traits_converter" shenanigans?

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +#endif
```suggestion
#endif // CGAL_CONVEX_HULL_HIERARCHY_3_H
```

2026-02-02 13:13 UTC, MaelRL commented on Convex_hull_3/include/CGAL/extreme_point_3.h
> +* computes the furthest point of the convex graph along the direction and returns the associated vertex; If not unique, a single vertex is returned.
Why require convexity here rather than using the same named parameters as in the hierarchy (compute_convex_hull)?

2026-02-02 13:13 UTC, MaelRL commented on Kernel_23/doc/Kernel_23/Concepts/Kernel.h
> +  typedef unspecified_type CompareScalarProduct_3;
No, here you are in the Kernel concept, that is you are saying "an object that is a model of `Kernel` must provide a type `X`". `X` is a "real" type, that you'll then use in real stuff.

And the documentation of that type `X` says: "`X` must be a model of the concept `CX`", which is a concept independent of `Kernel` and documents parameters and behavior that must be provided by `X`.

Thus, here the typedef here would be the model: `Compare_scalar_product_3` and it must be a model of the concept `CompareScalarProduct_3`, which you have to add where function object concepts live (FunctionObjectConcepts.h).

\+ add some tests for that new function object please.

2026-02-02 13:28 UTC, LeoValque commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * \cgalNamedParamsEnd
The `convex_hull_3` function that takes a mesh as input do no take traits https://doc.cgal.org/latest/Convex_hull_3/group__PkgConvexHull3Functions.html#gadc8318947c2133e56b2e56171b2ecd7d
It is probably something to add if we want clean the package.

2026-02-05 07:30 UTC, LeoValque commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *     \cgalParamType{a model of `ReadWritePropertyMap` whose value type is a point type}
I no longer need writable

2026-02-06 09:01 UTC, MaelRL commented
/force-build:v5

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/doc/Convex_hull_3/Convex_hull_3.txt
> +\authors Samuel Hornus, Susan Hert, Stefan Schirra and Leo Valque
```suggestion
\authors Samuel Hornus, Susan Hert, Stefan Schirra, and Leo Valque
```

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/distance.h
> +#if DOXYGEN_RUNNING
This is in experimental, but I would merge the three overloads into a single one like for do_intersect() while this is fresh.

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_3/do_intersect.h
> +* \brief checks if the convex hulls intersect or not.
```suggestion
* \brief checks whether two convex hulls intersect or not.
```

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  /// \ingroup PkgConvexHull3Ref
move it to the distance group

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +struct Convex_hull_hierarchy{
Let's give it the _3 suffix too

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  using Mesh = PolygonMesh;
I don't know if you need this? I would remove it if you don't: there are already different types of inputs that could create confusion, no need to add some.

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  ///         An internal property map for `CGAL::vertex_point_t` must be available, with a value type that is a model of `Kernel::Point_3`.
You require a Point from a CGAL kernel, this is stronger than model of `Kernel::Point_3`.

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  Convex_hull_hierarchy(RangeIterator begin, RangeIterator end, const Traits &traits = Traits()){
PointIterator is a better name because it explicits what you need + you need to define the requirements on the input iterator (the same as for convex_hull_3)

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +          /* ,typename NamedParameters=parameters::Default_named_parameters */
remove rather than comment

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  *         `Traits` must also be a model of the concept `IsStronglyConvexTraits_3`. Furthermore, `Traits` must define a type `PolygonMesh` that is a model of `MutableFaceGraph`.
Second sentence is obsolete.

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * Constructor taking the points associated to the vertices of `g`.
Technically it's only taking the graph

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  // /// returns a reference to the mesh stored by the class.
remove rather than comment

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/Convex_hull_hierarchy.h
> +  * computes the point of the convex hull whose orthogonal projection onto that direction is maximal and returns the associated vertex.
```suggestion
  * returns the vertex of the convex hull whose geometric position projected onto that direction is maximal.
```

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/extreme_point_3.h
> +* computes the furthest point of the convex graph along the direction and returns the associated vertex; If not unique, a single vertex is returned.
No longer convex requirement, but there is no named parameter to indicate whether it is convex or not?

2026-02-06 10:10 UTC, MaelRL commented on Convex_hull_3/include/CGAL/extreme_point_3.h
> +*   \cgalParamNBegin{geom_traits_converter}
hide this stuff everywhere

2026-02-12 14:29 UTC, sloriot commented
Successfully tested in CGAL-6.2-Ic-108

2026-03-17 14:22 UTC, merged