Triangulation_2:  Don't insert segment twice
CGAL/cgal pull request #6595
Opened 2022-05-19 11:02 UTC by afabri

## Summary of Changes

Inserting a segment as constraint more than once may cause problems when there are intersections. 
This PR addresses it in the `insert_constraints()`  function.  
We might add a `bool`  parameter in the API to document this.

## Release Management

* Affected package(s): Triangulation_2
* Issue(s) solved (if any): fix #0000, fix #0000,...
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

2022-05-19 11:31 UTC, sloriot commented on Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
> +      if(v1 != v2){
there should be a parameter to activate that only on demand IMO

2022-05-19 12:01 UTC, sloriot commented on Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
> +          std::pair<Vertex_handle,Vertex_handle> p = (v1 < v2)? std::make_pair(v1,v2): std::make_pair(v2,v1);
`CGAL::make_sorted_pair()`

2022-05-19 21:01 UTC, afabri commented
/build:v0

2022-05-26 15:58 UTC, sloriot commented
Successfully tested in CGAL-5.5-Ic-92

2022-06-16 12:14 UTC, sloriot commented
I'm fine with the new API introduced. @lrineau Do we need a small feature?

2022-06-17 07:41 UTC, lrineau commented
> I'm fine with the new API introduced. @lrineau Do we need a small feature?

It is not me to decide. That depends if you want to follow the rules of the CGAL project.

Know that I am opposed to API using `bool` parameters. It should be a named parameter, or an enum.

2022-07-04 09:33 UTC, sloriot commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> -std::size_t insert_constraints(ConstraintIterator first, ConstraintIterator last);
@afabri could you tunr the `bool` into an enum?

2023-01-30 13:42 UTC, sloriot commented
This PR seems useful, @afabri what is its status?

2023-04-06 16:38 UTC, sloriot commented
ping @afabri

2024-10-18 15:52 UTC, sloriot commented
Successfully tested in CGAL-6.0.1-Ic-351

2024-10-18 20:10 UTC, lrineau commented
This PR is marked with https://github.com/CGAL/cgal/labels/Tested but it still a draft, left untouched for two years. @afabri Was it not developed in response to a bug report?

2025-10-07 14:32 UTC, sloriot commented on Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
> +                                    bool check_duplicates = false)
shall we make is a constexpr bool so that we can use a constexpr if?

2025-10-07 14:32 UTC, sloriot commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +Same as above except that the function check for duplicates.
```suggestion
Same as `insert_constraints(begin,end)` except that duplicated pairs of points are only considered once.
```

2025-10-07 14:32 UTC, sloriot commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +std::size_t insert_constraints(PointIterator points_first, PointIterator points_last,
```suggestion
std::size_t insert_unique_constraints(PointIterator points_first, PointIterator points_last,
```

2025-10-07 14:32 UTC, sloriot commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +Same as above except that the function check for duplicates.
```suggestion
Same as insert_constraint(points_first, points_last, indices_first, indices_last)` except that duplicated pair of points are only considered once.
```

2025-10-07 16:32 UTC, LeoValque commented on Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
> +                                    bool check_duplicates = false)
I replace with the attribute by a template parameter and use a constexpr

2025-10-08 09:12 UTC, albert-github commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +Same as insert_constraint(points_first, points_last, indices_first, indices_last)` except that duplicated pair of points are only considered once.
Looks like a sole backtick at the end of the line
Found by: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-6.2-Ic-14/logs_master/Triangulation_2.log, rest might be collateral damage.

2025-10-17 08:08 UTC, sloriot commented
Successfully tested in CGAL-6.2-Ic-20

2025-10-21 21:32 UTC, MaelRL requested changes

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +case of intersecting segments and non-exact constructions.
Is this supposed to mean "it might be worth it to pay the price of uniqueness checks because inserting the same constraints multiple times can be the source of issues [...]"? It's not completely clear as is.

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +Same as `insert_constraint(points_first, points_last, indices_first, indices_last)` except that duplicated pair of points are only considered once.
```suggestion
Same as `insert_constraint(points_first, points_last, indices_first, indices_last)` except that duplicated pairs of points are only considered once.
```

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +\tparam IndicesIterator is an `InputIterator` with `std::pair<Int, Int>` where `Int` is an integral type implicitly convertible to `std::size_t`
would be nice to harmonize "must be", "is an", "\return" (at the end, not before \tparam), "with value type", etc.

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +Same as above except that each constraints is given as a pair of indices of the points
```suggestion
Same as above except that each constraint is given as a pair of indices of the points
```

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +Same as `insert_constraint(points_first, points_last, indices_first, indices_last)` except that duplicated pair of points are only considered once.
```suggestion
Same as `insert_constraint(points_first, points_last, indices_first, indices_last)` except that duplicated pairs of points are only considered once.
```

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
> +#include <boost/functional/hash.hpp>
```suggestion
#include <boost/functional/hash.hpp>

#include <iterator>
#include <unordered_set>
#include <vector>
```

2025-10-21 21:32 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +std::size_t insert_unique_constraints(PointIterator points_first, PointIterator points_last,
The overload `Constrained_triangulation_2::insert_constraints` does not have a "_unique_" version?

2025-12-01 13:52 UTC, LeoValque commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +case of intersecting segments and non-exact constructions.
I will add "Indeed, when an inserted segment is subdivided, the resulting subsegments are slightly displaced by numerical error and may therefore intersect the next insertion of the same segment, creating additional vertices at each insertion."
is it good?

2025-12-01 16:22 UTC, LeoValque commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +std::size_t insert_unique_constraints(PointIterator points_first, PointIterator points_last,
Do you mean the version that takes a range of points and creates a polyline from them? I can make a “unique” variant for that, but it will only be useful if the range loops back on itself.

2025-12-19 09:22 UTC, MaelRL commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +case of intersecting segments and non-exact constructions.
:+1:

2025-12-19 09:47 UTC, albert-github commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
> +\note points are inserted even if they are not endpoint of a constraint.
endpoint -> an endpoint

2025-12-19 09:47 UTC, albert-github commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +\return the number of inserted points..
End with 2 dots (`.`) instead of 1

2025-12-19 09:47 UTC, albert-github commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +Int` is an integral type implicitly convertible to `std::size_t`
`` `Int` `` should not be distributed over 2 lines

2025-12-19 09:47 UTC, albert-github commented on Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> +\note points are inserted even if they are not endpoint of a constraint.
See above: endpoint -> an endpoint

2025-12-19 10:10 UTC, lrineau commented
/build:v1

2026-02-03 13:09 UTC, sloriot commented
Successfully tested in CGAL-6.2-Ic-101

2026-02-03 13:18 UTC, merged