Mesh_3: Add test for determinism when not checking for features
CGAL/cgal pull request #7098
Opened 2022-11-30 09:19 UTC by afabri

## Summary of Changes

Add a testcase as suggested in the issue. 

## Release Management

* Affected package(s): Mesh_3
* Issue(s) solved (if any): fix #6958

2022-11-30 09:23 UTC, afabri commented
@janetournois I kept the domain and the cube, but I only switched off the detection of features. 
@sloriot I am also wondering about the [CMakeLists.txt](https://github.com/CGAL/cgal/blob/master/Mesh_3/test/Mesh_3/CMakeLists.txt#L88).   Why does the original test `test_meshing_determinism.cpp` not need to link against TBB.   Or is the whole block of linking no longer necessary?

2022-11-30 09:47 UTC, sloriot commented
If you don't link with TBB then the sequential version of the mesher will be used. If the test/example you mentioned is not in the list of what is linked with TBB it has most probably be forgotten.

2022-12-01 08:19 UTC, janetournois commented
It is not linked with TBB because the parallel version is known to be non-deterministic. We want to test the sequential version

2022-12-01 09:23 UTC, janetournois requested changes

2022-12-01 09:23 UTC, janetournois commented on Mesh_3/test/Mesh_3/test_meshing_without_features_determinism.cpp
> +#include <CGAL/Polyhedral_mesh_domain_with_features_3.h>
This can be replaced by `Polyhedra_mesh_domain_3.h` to be entirely out of the "with features" framework

2022-12-01 09:23 UTC, janetournois commented on Mesh_3/test/Mesh_3/test_meshing_without_features_determinism.cpp
> +#include <CGAL/Polyhedral_mesh_domain_with_features_3.h>
```suggestion
#include <CGAL/Polyhedral_mesh_domain_3.h>
```

2022-12-01 09:23 UTC, janetournois commented on Mesh_3/test/Mesh_3/test_meshing_without_features_determinism.cpp
> +  typedef CGAL::Polyhedral_mesh_domain_with_features_3<K> Mesh_domain;
```suggestion
  typedef CGAL::Polyhedral_mesh_domain_3<K> Mesh_domain;
```

2022-12-01 09:29 UTC, janetournois commented
Right, I had forgotten that point. Then, both determinism tests should be added to the list to be linked with TBB

2022-12-06 07:53 UTC, sloriot commented
Test failing on several platforms like [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-128/Mesh_3/TestReport_lrineau_Ubuntu-Latest.gz)

2022-12-06 12:27 UTC, afabri commented
> Test failing on several platforms like [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-128/Mesh_3/TestReport_lrineau_Ubuntu-Latest.gz)

@janetournois it is your turn now.

2022-12-12 09:35 UTC, janetournois commented
Actually this already is a known issue, see #4469

2022-12-12 10:55 UTC, janetournois commented
PR #3368 and #4795 have improved but not fully fixed the determinism in parallel mode with one thread problem.
I'm working on it

2022-12-13 14:09 UTC, lrineau commented
> Insertion of far points for parallel code was not deterministic. It's fixed now.
> 
> @lrineau I don't think that here, we want to keep the ability to change the seed (as we did in the mesh domains for initialization), so I hardcoded `CGAL::Random(0)` as generator for `Random_points_on_sphere_3`. Do you agree with that?

Yes, that is fine.

2022-12-13 14:54 UTC, janetournois approved these changes

2022-12-29 20:24 UTC, sloriot commented
Successfully tested in CGAL-5.6-Ic-145

2023-01-27 20:18 UTC, merged