Converter to qpolygon
CGAL/cgal pull request #7357
Opened 2023-03-29 14:47 UTC by mentonin

## Summary of Changes

Adds converter from `std::list<K::Point_2>` to `QPolygonF` that was documented but not implemented. Also fixes documentation for the converter in the opposite direction to match the actual implementation and adds documentation for the converter from `K::Circular_arc_point_2` to `QPointF`.

## Release Management

* Affected package(s): Qt

2023-03-30 08:35 UTC, lrineau requested changes
Thanks for your contribution.

I found out two errors (typos) that are easy to fix, before this pull-request can be accepted.

2023-03-30 08:35 UTC, lrineau commented on GraphicsView/doc/GraphicsView/CGAL/Qt/Converter.h
> +
```suggestion
/*!
Converts a circular arc point.
*/
QPointF operator()(K::Circular_arc_point_2);

```

2023-04-06 13:04 UTC, mentonin commented
Fixed typos

2023-04-16 20:15 UTC, sloriot commented
Successfully tested in CGAL-5.6-Ic-223

2023-04-17 08:19 UTC, merged