Prevent out-of-bound warnings
CGAL/cgal pull request #7907
Opened 2023-12-05 08:08 UTC by sloriot

Fixes warnings for example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-121/Mesh_3/TestReport_lrineau_Fedora-rawhide-Release.gz)

2023-12-05 09:29 UTC, lrineau requested changes
As I said in a private discussion, I am opposed to that change, unless all other possible ways to fix that warning are tested before (and in particular `CGAL_assume(i != j)` in CGAL functions using that table).

2023-12-05 12:58 UTC, lrineau approved these changes

2023-12-05 13:10 UTC, afabri commented
Does the `assume` make the warning go away ????

2023-12-06 08:06 UTC, sloriot commented
Successfully tested in CGAL-6.0-Ic-122 (the warning is gone)

2023-12-11 13:05 UTC, merged