Adding 3D barycentric coordinates for convex polyhedra
CGAL/cgal pull request #8267
Opened 2024-06-07 12:28 UTC by sloriot

## Summary of Changes

New package for 3D barycentric coordinates in a convex polyhedron

## Release Management

* Affected package(s): New package
* Feature/Small Feature (if any): [here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Barycentric_coordinates_3)
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership: GF

## TODO
- [x] check branch size (@sloriot)
- [x] check usage of `get_tolerance()` from `Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/internal/utils_3.h`

2024-06-07 13:00 UTC, sloriot commented
/build:v1

2024-06-07 14:11 UTC, sloriot commented
cc @antoniospg :)

2024-06-15 07:47 UTC, danston commented
@sloriot No, for center query in a cube there are no edge cases. The sum should be strictly positive because all weights are positive. My guess would be that certain weights are positive and certain are negative so they sum up to zero. If this is a case, most likely the orientation of faces is different from what it has been when the test was developed because it did pass when Antonio worked on it. Could that be that this line
```
CGAL::make_hexahedron(p0, p1, p2, p3, p4, p5, p6, p7, polyhedron, CGAL::parameters::do_not_triangulate_faces(false));
```
produces different results from this one:
```
PMP::triangulate_faces(faces(polyhedron), polyhedron);
```
In any case for such a simple test, I would first check how the cube looks like, orientation of its faces, and values of the weights.

2024-06-19 09:43 UTC, danston commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Wachspress_coordinates_3.h
> +    FT compute_wp_vertex_query(const Vertex& vertex, const Point_3& query){
@sloriot The issue is probably coming from this method. There is suspicious negation of the first face normal, which is not coherent with other normals used here. Implementations of other MV and DH coordinates do not have this. My guess would be that this method does not return the same weights for the same mesh but differently oriented faces, which should not be the case. What is important here is to have consistent normals as indicated in the [original paper](https://www.cs.wustl.edu/~taoju/research/generalbary_new.pdf). Maybe just try to remove the negation in line 269 and see what happens? 

There are multiple formulas to compute WP coordinates. I do not remember which one Antonio used here. Maybe it is worth using all formulas from the same paper to be consistent. Finally, another test that is easy to do is to change WP to DH coordinates in this test and see if it works. If I remember correctly for such a simple case (center point in a cube) WP and DH should produce exactly the same result.

2025-02-21 22:41 UTC, sloriot commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Wachspress_coordinates_3.h
> +    FT compute_wp_vertex_query(const Vertex& vertex, const Point_3& query){
I went back to Meyers' paper and updated the formula. This test passes but now  `test_dh_weights_3` and `test_edge_cases` don't.  TBC

2025-02-24 06:22 UTC, sloriot commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Wachspress_coordinates_3.h
> +    FT compute_wp_vertex_query(const Vertex& vertex, const Point_3& query){
Fixed!

2025-04-03 06:39 UTC, soesau commented
/build:v0

2025-04-10 09:24 UTC, soesau commented
/build:v0

2025-04-11 14:10 UTC, soesau commented
/build:v0

2025-09-24 10:08 UTC, soesau commented
/build:v0

2025-09-25 12:52 UTC, afabri requested changes

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Discrete_harmonic_coordinates_3.h
> +typename VertexToPointMap = typename boost::property_map<TriangleMesh, CGAL::vertex_point_t>::const_type>
Maybe `VertexPointMap` without `To` ?

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Discrete_harmonic_coordinates_3.h
> +  Discrete_harmonic_coordinates_3(const TriangleMesh& triangle_mesh,
`triangle_mesh` ->  `tmesh`   as in PMP.

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Discrete_harmonic_coordinates_3.h
> +    \pre num_vertices(triangle_mesh) >= 4.
backticks ??
Also add `is_triangle_mesh(tmesh)`

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/Discrete_harmonic_coordinates_3.h
> +    After the coordinates \f$b_i\f$ with \f$i = 1\dots n\f$ are computed, where
Does it make sense to start with `1`  instead of `0` ?

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/doc/Barycentric_coordinates_3/Barycentric_coordinates_3.txt
> +in the space and with respect to any non-degenerate tetrahedron. No special cases are handled.
remove the "the"?

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/boundary_coordinates_3.h
> +  with respect to the vertices of a simple `polyhedron`, that is one
What is the meaning of "simple"?

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/include/CGAL/Barycentric_coordinates_3/tetrahedron_coordinates.h
> +  \return a array `std::array<GeomTraits::FT, 4>`
```suggestion
  \return an array `std::array<GeomTraits::FT, 4>`
```

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/doc/Barycentric_coordinates_3/Barycentric_coordinates_3.txt
> +two CGAL functions: CGAL::to_double() and CGAL::sqrt(). In this implementation, discrete harmonic
```suggestion
two %CGAL functions: CGAL::to_double() and CGAL::sqrt(). In this implementation, discrete harmonic
```

2025-09-25 12:52 UTC, afabri commented on Barycentric_coordinates_3/doc/Barycentric_coordinates_3/Barycentric_coordinates_3.txt
> +\section gbc_3_acknowledgments Acknowledgments
Remove in case it stays empty.

2025-11-20 13:36 UTC, soesau commented
/build:v0

2025-12-12 17:39 UTC, afabri commented on Barycentric_coordinates_3/examples/Barycentric_coordinates_3/tetrahedron_coordinates.cpp
> +//Typedefs
```suggestion
```

2025-12-12 17:41 UTC, afabri commented on Barycentric_coordinates_3/examples/Barycentric_coordinates_3/mean_value_coordinates_3.cpp
> +namespace PMP = CGAL::Polygon_mesh_processing;
```suggestion
```

2025-12-12 17:42 UTC, afabri commented on Barycentric_coordinates_3/examples/Barycentric_coordinates_3/shape_deformation_3.cpp
> +namespace PMP = CGAL::Polygon_mesh_processing;
```suggestion
```

2025-12-12 17:45 UTC, afabri commented on Barycentric_coordinates_3/examples/Barycentric_coordinates_3/wachspress_coordinates_3.cpp
> +namespace PMP = CGAL::Polygon_mesh_processing;
Again, no need for `PMP`.   But maybe create `BC`  to shorten the namespace, but do NOT shorten to ` CP3`  and `WP` as they are the star of the example but reduced to two characters.

2025-12-12 17:46 UTC, afabri commented on Barycentric_coordinates_3/examples/Barycentric_coordinates_3/wachspress_coordinates_3.cpp
> +#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>
```suggestion
```

2025-12-15 08:27 UTC, soesau commented
/build:v0

2025-12-30 08:55 UTC, sloriot commented
Tests are red in CGAL-6.2-Ic-73, examples have some warnings

2025-12-31 10:41 UTC, sloriot commented
Only one test failing on some platforms in CGAL-6.2-Ic-74

2026-01-08 07:51 UTC, soesau commented
/build:v0

2026-01-09 17:39 UTC, soesau commented
/build:v0

2026-01-13 13:09 UTC, afabri commented on Barycentric_coordinates_3/doc/Barycentric_coordinates_3/PackageDescription.txt
> +namespace CGAL {
In fact those two must be removed.   And in the listing below the classes and free  functions must  be prefixed with the namespace.   And while you at it, also fix it [here ](https://doc.cgal.org/latest/Barycentric_coordinates_2/group__PkgBarycentricCoordinates2Ref.html)

2026-01-13 13:10 UTC, afabri commented on Barycentric_coordinates_3/doc/Barycentric_coordinates_3/PackageDescription.txt
> +namespace CGAL {
With thos two I mean line 1 and 2.

2026-01-13 13:32 UTC, soesau commented on Barycentric_coordinates_3/doc/Barycentric_coordinates_3/PackageDescription.txt
> +namespace CGAL {
fixed

2026-01-13 13:57 UTC, soesau commented
/build:v0

2026-01-15 17:25 UTC, sloriot commented
Successfully tested in CGAL-6.2-Ic-83

2026-02-03 14:13 UTC, merged